export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const ADD_SURNAME_REQUEST = 'ADD_SURNAME_REQUEST';
export const ADD_SURNAME_SUCCESS = 'ADD_SURNAME_SUCCESS';
export const ADD_SURNAME_FAILURE = 'ADD_SURNAME_FAILURE';

export const GET_SURNAMES_REQUEST = 'GET_SURNAMES_REQUEST';
export const GET_SURNAMES_SUCCESS = 'GET_SURNAMES_SUCCESS';
export const GET_SURNAMES_FAILURE = 'GET_SURNAMES_FAILURE';

export const DELETE_SURNAME_REQUEST = 'DELETE_SURNAME_REQUEST';
export const DELETE_SURNAME_SUCCESS = 'DELETE_SURNAME_SUCCESS';
export const DELETE_SURNAME_FAILURE = 'DELETE_SURNAME_FAILURE';

export const UPDATE_SURNAME_REQUEST = 'UPDATE_SURNAME_REQUEST';
export const UPDATE_SURNAME_SUCCESS = 'UPDATE_SURNAME_SUCCESS';
export const UPDATE_SURNAME_FAILURE = 'UPDATE_SURNAME_FAILURE';

export const USER_ENUM_REQUEST = 'USER_ENUM_REQUEST';
export const USER_ENUM_SUCCESS = 'USER_ENUM_SUCCESS';
export const USER_ENUM_FAIL = 'USER_ENUM_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SEARCH_REQUEST = 'USER_SEARCH_REQUEST';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL';

export const USER_TOPSELLERS_LIST_REQUEST = 'USER_TOPSELLERS_LIST_REQUEST';
export const USER_TOPSELLERS_LIST_SUCCESS = 'USER_TOPSELLERS_LIST_SUCCESS';
export const USER_TOPSELLERS_LIST_FAIL = 'USER_TOPSELLERS_LIST_FAIL';   
